# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'

steps:

- task: DotNetCoreCLI@2
  displayName: Install Report Generator Tool
  inputs:
    command: 'custom'
    custom: 'tool install'
    arguments: '-g dotnet-reportgenerator-globaltool'

- task: DotNetCoreCLI@2
  displayName: Install Sonar Scanner Tool
  inputs:
    command: 'custom'
    custom: 'tool install'
    arguments: '-g dotnet-sonarscanner'

- task: DotNetCoreCLI@2
  displayName: "Restore"
  inputs:
    command: 'restore'
    feedsToUse: 'select'

- task: DotNetCoreCLI@2
  displayName: "Build"
  inputs:
    command: 'build'
    arguments: '--no-restore --configuration $(buildConfiguration)'

- task: DotNetCoreCLI@2
  displayName: "Test"
  inputs:
    command: 'test'
    arguments: '--no-build --collect:"XPlat Code Coverage" --configuration $(buildConfiguration)'