//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Outkeep.Hosting.Azure.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Outkeep.Hosting.Azure.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear operation failed.
        /// </summary>
        internal static string Exception_ClearOperationFailed {
            get {
                return ResourceManager.GetString("Exception_ClearOperationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear operation failed with HTTP Status Code {0}.
        /// </summary>
        internal static string Exception_ClearOperationFailedWithHttpStatusCode_X {
            get {
                return ResourceManager.GetString("Exception_ClearOperationFailedWithHttpStatusCode_X", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to InsertOrReplace operation failed.
        /// </summary>
        internal static string Exception_InsertOrReplaceOperationFailed {
            get {
                return ResourceManager.GetString("Exception_InsertOrReplaceOperationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to InsertOrReplace operation failed with HTTP Status Code {0}.
        /// </summary>
        internal static string Exception_InsertOrReplaceOperationFailedWithHttpStatusCode_X {
            get {
                return ResourceManager.GetString("Exception_InsertOrReplaceOperationFailedWithHttpStatusCode_X", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid cloud storage account connection string.
        /// </summary>
        internal static string Exception_InvalidCloudStorageAccountConnectionString {
            get {
                return ResourceManager.GetString("Exception_InvalidCloudStorageAccountConnectionString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Started azure table registry grain storage named {StorageName} using table {TableName}.
        /// </summary>
        internal static string Log_StartedAzureTableRegistryGrainStorageNamed_X_UsingTable_X {
            get {
                return ResourceManager.GetString("Log_StartedAzureTableRegistryGrainStorageNamed_X_UsingTable_X", resourceCulture);
            }
        }
    }
}
