//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Outkeep.Hosting.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Outkeep.Hosting.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not open a dynamic port for exclusive use.
        /// </summary>
        internal static string ExceptionCouldNotOpenADynamicPortForExclusiveUse {
            get {
                return ResourceManager.GetString("ExceptionCouldNotOpenADynamicPortForExclusiveUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected endpoint type.
        /// </summary>
        internal static string ExceptionUnexpectedEndpointType {
            get {
                return ResourceManager.GetString("ExceptionUnexpectedEndpointType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Outkeep Server Started.
        /// </summary>
        internal static string LogOutkeepServerStarted {
            get {
                return ResourceManager.GetString("LogOutkeepServerStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Outkeep Server Starting.
        /// </summary>
        internal static string LogOutkeepServerStarting {
            get {
                return ResourceManager.GetString("LogOutkeepServerStarting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Outkeep Server Stopped.
        /// </summary>
        internal static string LogOutkeepServerStopped {
            get {
                return ResourceManager.GetString("LogOutkeepServerStopped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Outkeep Server Stopping.
        /// </summary>
        internal static string LogOutkeepServerStopping {
            get {
                return ResourceManager.GetString("LogOutkeepServerStopping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no free ports within the input range.
        /// </summary>
        internal static string ThereAreNoFreePortsWithinTheInputRange {
            get {
                return ResourceManager.GetString("ThereAreNoFreePortsWithinTheInputRange", resourceCulture);
            }
        }
    }
}
