//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Outkeep.Api.Rest.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Outkeep.Api.Rest.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Outkeep REST API Started.
        /// </summary>
        internal static string OutkeepRestApiStarted {
            get {
                return ResourceManager.GetString("OutkeepRestApiStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Outkeep REST API Starting.
        /// </summary>
        internal static string OutkeepRestApiStarting {
            get {
                return ResourceManager.GetString("OutkeepRestApiStarting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Outkeep REST API Stopped.
        /// </summary>
        internal static string OutkeepRestApiStopped {
            get {
                return ResourceManager.GetString("OutkeepRestApiStopped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Outkeep REST API Stopping.
        /// </summary>
        internal static string OutkeepRestApiStopping {
            get {
                return ResourceManager.GetString("OutkeepRestApiStopping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starting activity {ActivityId}.
        /// </summary>
        internal static string StartingActivity_X {
            get {
                return ResourceManager.GetString("StartingActivity_X", resourceCulture);
            }
        }
    }
}
