//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Outkeep.Core.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Outkeep.Core.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cache entry for key {0} already has a registered callback.
        /// </summary>
        internal static string Exception_CacheEntryFor_X_AlreadyHasARegisteredCallback {
            get {
                return ResourceManager.GetString("Exception_CacheEntryFor_X_AlreadyHasARegisteredCallback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cache entry for key {0} is comitted and does not allow this operation.
        /// </summary>
        internal static string Exception_CacheEntryFor_X_IsCommittedAndDoesNotAllowThisOperation {
            get {
                return ResourceManager.GetString("Exception_CacheEntryFor_X_IsCommittedAndDoesNotAllowThisOperation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cache entry for key {0} is uncomitted and does not allow this operation.
        /// </summary>
        internal static string Exception_CacheEntryFor_X_IsUncommittedAndDoesNotAllowThisOperation {
            get {
                return ResourceManager.GetString("Exception_CacheEntryFor_X_IsUncommittedAndDoesNotAllowThisOperation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The cache entry for key {0} must have a size greater than zero.
        /// </summary>
        internal static string Exception_CacheEntryFor_X_MustHaveSizeGreaterThanZero {
            get {
                return ResourceManager.GetString("Exception_CacheEntryFor_X_MustHaveSizeGreaterThanZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The cache entry for key {0} must have a size lesser than or equal capacity of {1}.
        /// </summary>
        internal static string Exception_CacheEntryFor_X_MustHaveSizeLesserThanOrEqualCapacityOf_X {
            get {
                return ResourceManager.GetString("Exception_CacheEntryFor_X_MustHaveSizeLesserThanOrEqualCapacityOf_X", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cache file {0} contains key {1} yet we expected {2}.
        /// </summary>
        internal static string Exception_CacheFile_X_ContainsKey_X_YetWeExpected_X {
            get {
                return ResourceManager.GetString("Exception_CacheFile_X_ContainsKey_X_YetWeExpected_X", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cache file {0} contains null key yet we expected {1}.
        /// </summary>
        internal static string Exception_CacheFile_X_ContainsNullKey_YetWeExpected_X {
            get {
                return ResourceManager.GetString("Exception_CacheFile_X_ContainsNullKey_YetWeExpected_X", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cache file {0} does not contain expected key {1}.
        /// </summary>
        internal static string Exception_CacheFile_X_DoesNotContainExpectedKey_X {
            get {
                return ResourceManager.GetString("Exception_CacheFile_X_DoesNotContainExpectedKey_X", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cache file {0} does not contain a value.
        /// </summary>
        internal static string Exception_CacheFile_X_ForKey_X_DoesNotContainValue {
            get {
                return ResourceManager.GetString("Exception_CacheFile_X_ForKey_X_DoesNotContainValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The cache key {0} is not valid for this storage provider..
        /// </summary>
        internal static string Exception_CacheKey_X_IsNotValidForThisStorageProvider {
            get {
                return ResourceManager.GetString("Exception_CacheKey_X_IsNotValidForThisStorageProvider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to StorageDirectory must be configured.
        /// </summary>
        internal static string Exception_CacheStorageOptions_StorageDirectory_MustBeConfigured {
            get {
                return ResourceManager.GetString("Exception_CacheStorageOptions_StorageDirectory_MustBeConfigured", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to StorageDirectory {0} is not a well formed absolute URI.
        /// </summary>
        internal static string Exception_CacheStorageOptions_StorageDirectory_X_IsNotWellAbsoluteFormed {
            get {
                return ResourceManager.GetString("Exception_CacheStorageOptions_StorageDirectory_X_IsNotWellAbsoluteFormed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Condition for type {0} with value {1} is not supported.
        /// </summary>
        internal static string Exception_ConditionForType_X_WithValue_X_IsNotSupported {
            get {
                return ResourceManager.GetString("Exception_ConditionForType_X_WithValue_X_IsNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to clear cache file {0} for key {1}.
        /// </summary>
        internal static string Exception_FailedToClearCacheFile_X_ForKey_X {
            get {
                return ResourceManager.GetString("Exception_FailedToClearCacheFile_X_ForKey_X", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to read cache file.
        /// </summary>
        internal static string Exception_FailedToReadCacheFile {
            get {
                return ResourceManager.GetString("Exception_FailedToReadCacheFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to write cache file &apos;{0}&apos; for key &apos;{1}&apos;.
        /// </summary>
        internal static string Exception_FailedToWriteCacheFile_X_For_Key_X {
            get {
                return ResourceManager.GetString("Exception_FailedToWriteCacheFile_X_For_Key_X", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The cache director could not compact the cache to target capacity of {Size}.
        /// </summary>
        internal static string Log_CacheDirectorCannotCompactToTargetSizeOf_X {
            get {
                return ResourceManager.GetString("Log_CacheDirectorCannotCompactToTargetSizeOf_X", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cache file {Path} for key {Key} not found.
        /// </summary>
        internal static string Log_CacheFile_X_ForKey_X_NotFound {
            get {
                return ResourceManager.GetString("Log_CacheFile_X_ForKey_X_NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completed overcapacity compaction with final size of {Size}.
        /// </summary>
        internal static string Log_CompletedOvercapacityCompactionWithSizeOf_X {
            get {
                return ResourceManager.GetString("Log_CompletedOvercapacityCompactionWithSizeOf_X", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleted cache file {Path} for key {Key}.
        /// </summary>
        internal static string Log_DeletedCacheFile_X_ForKey_X {
            get {
                return ResourceManager.GetString("Log_DeletedCacheFile_X_ForKey_X", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The eviction callback for key {Key} and cause {Cause} failed.
        /// </summary>
        internal static string Log_EvictionCallbackForKey_X_WithCause_X_Failed {
            get {
                return ResourceManager.GetString("Log_EvictionCallbackForKey_X_WithCause_X_Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed operation on cache file {Path} for key {Key}.
        /// </summary>
        internal static string Log_FailedOperationOnCacheFile_X_ForKey_X {
            get {
                return ResourceManager.GetString("Log_FailedOperationOnCacheFile_X_ForKey_X", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Read cache file {Path} for key {Key} with value size of {Size} bytes.
        /// </summary>
        internal static string Log_ReadCacheFile_X_ForKey_X_WithValueSizeOf_X_Bytes {
            get {
                return ResourceManager.GetString("Log_ReadCacheFile_X_ForKey_X_WithValueSizeOf_X_Bytes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scheduling overcapacity compaction.
        /// </summary>
        internal static string Log_SchedulingOvercapacityCompaction {
            get {
                return ResourceManager.GetString("Log_SchedulingOvercapacityCompaction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starting overcapacity compaction with current size of {Size}.
        /// </summary>
        internal static string Log_StartingOvercapacityCompactionWithSizeOf_X {
            get {
                return ResourceManager.GetString("Log_StartingOvercapacityCompactionWithSizeOf_X", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrote cache file {Path} for key {Key} with value size of {Size} bytes.
        /// </summary>
        internal static string Log_WroteCacheFile_X_ForKey_X_WithValueSizeOf_X_Bytes {
            get {
                return ResourceManager.GetString("Log_WroteCacheFile_X_ForKey_X_WithValueSizeOf_X_Bytes", resourceCulture);
            }
        }
    }
}
